FROM python:3.8.0-slim

RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean

RUN mkdir ./app
#ADD  ./app
WORKDIR ./app
#COPY ./requirements.txt .
COPY ./svdcut.py .
COPY ./svdcut.out .
#RUN pip install -r requirements.txt
RUN pip install gvar
RUN pip install lsqfit
CMD ["python", "svdcut.py"]


